name: docker-build-and-push-main

on:
  schedule:
    - cron: 0 0 1,15 * *
  workflow_dispatch:
    inputs:
      publish_packages:
        description: 'Publish packages to GitHub Package Registry'
        required: true
        default: false
        type: boolean
      release_version:
        description: 'Release version(If it is a release, specify the tag name for it)'
        required: false
        default: ''
        type: string

jobs:
  docker-build-and-push-main:
    runs-on: [self-hosted, linux, X64]
    strategy:
      fail-fast: false
      matrix:
        name:
          - no-cuda
          - cuda
        include:
          - name: no-cuda
            base_image_env: base_image
            lib_dir: x86_64
            setup-args: --no-nvidia
            additional-tag-suffix: ""
          - name: cuda
            base_image_env: base_image
            lib_dir: x86_64
            additional-tag-suffix: -cuda
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Load env
        run: |
          cat amd64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          if [ "$(uname -m)" = "aarch64" ]; then
            cat arm64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          fi

      - name: Build 'autoware-openadk'
        uses: ./.github/actions/docker-build-and-push
        with:
          bake-target: autoware-openadk
          build-args: |
            *.platform=linux/amd64
            *.args.ROS_DISTRO=${{ env.rosdistro }}
            *.args.BASE_IMAGE=${{ env[format('{0}', matrix.base_image_env)] }}
            *.args.SETUP_ARGS=${{ matrix.setup-args }}
            *.args.LIB_DIR=${{ matrix.lib_dir }}
          tag-prefix: ${{ env.rosdistro }}-
          tag-suffix: ${{ matrix.additional-tag-suffix }}-amd64

      - name: Show disk space
        run: |
          df -h
