name: setup-universe

on:
  pull_request:

jobs:
  load-env:
    uses: ./.github/workflows/load-env.yaml

  setup-universe:
    needs: load-env
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run setup script
        run: |
          ./setup-dev-env.sh -y -v universe
